### PR TITLE
#21 Support nested properties in code-completion

### PR DESCRIPTION
**Pull request by agudian**
Supports nested properties in source and target, supports multiple source parameters (the source-path then needs to start with the source parameter name).

We still don't have a proper test framework, which starts to be really annoying... 🙁  But I tested it in various of our mappers in the processor tests...

### CODE REVIEW

**Comment by agudian** [comment]
I've untangled the proposal classes a bit and moved them to a seperate package (similar to the quick-fixes).

I also added an icon that shows up in the list of Proposals in `Preferences->Java->Editor->Content Assist->Advanced`.

**Comment by agudian** [comment]
@gunnarmorling, @sjaakd, @filiphr: anyone adventurous enough to take a look at this PR or maybe try it out? Would be cool to let users try it and have fun with the improved stuff in 1.2.0.Beta1... :)

**Comment by sjaakd** [comment]
I pass. I'm not an eclipse user.. Trying to move slowly to IntelliJ 👍

**Comment by agudian** [comment]
> I pass. I'm not an eclipse user.. Trying to move slowly to IntelliJ 👍

Then at least add your vote to these two, please:
* https://youtrack.jetbrains.com/issue/IDEA-1506210
* https://youtrack.jetbrains.com/issue/IDEABKL-7174

... then it might become as good as Eclipse in that perspective... 😛

**Comment by sjaakd** [comment]
I'll do my best :smile:

**Comment by filiphr** [comment]
I am also not an Eclipse user, but IntelliJ one 😄.

And I think you meant https://youtrack.jetbrains.com/issue/IDEA-150621 😄.

I tried it quickly and for nested it behaves OK.  It doesn't find usages, that is correct right? And it doesn't work when you have only one source parameter. For example in the `FishTankMapper` the source does not work for the `mapAsWell` method.

**Comment by agudian** [comment]
> It doesn't find usages, that is correct right?

Right, that still could be added at some point...

> And it doesn't work when you have only one source parameter. For example in the FishTankMapper the source does not work for the mapAsWell method.

Haaa, yes... If there is only one source parameter, I simply guess that the first element is already a property and not the parameter. I should fix that...

**Comment by sjaakd** [comment]
Hey guys.. for fun.. just typed MapStruct in InteliJ issue registration. 7 hits..

**Comment by gunnarmorling** [comment]
Couldn't try it out, but if you tested it I trust it's good :)

**Comment by gunnarmorling** [comment]
@agudian Should we push a new build to the Eclipse market place? The current version is quite old and download numbers are rising it seems.

**Comment by agudian** [comment]
> Should we push a new build to the Eclipse market place? The current version is quite old and download numbers are rising it seems.

Good idea, I'll take care of it. It basically only means publishing the archived files from Jenkins to bintray...

If only that UI was a bit more forthcoming, it would have been an easy thing and wouldn't have taken me almost an hour now... 😁 But if you have an older version installed, Eclipse should show you an update if you search for updates... Or directly deliver the new version on a fresh installation.

**Comment by gunnarmorling** [comment]
Cool, thanks. Nice to see progress in the plug-in!

**Pull request merged**
